export const productNameInputName = 'name'
export const productDescriptionInputName = 'description'
export const productPriceInputName = 'price'
export const productCategoryIdInputName = 'category-id'
export const productImagesInputName = 'images'
export const productKeywordsInputName = 'keywords'
export const productInfoInputName = 'info'