export const PRODUCT_NAME_MINIMAL_LENGTH = 1
export const PRODUCT_DESCRIPTION_MINIMAL_NAME = 1
export const PRODUCT_MINIMAL_PRICE = 0.1
export const PRODUCT_CATEGORY_ID_MINIMAL_LENGTH = 1
export const PRODUCT_MINIMAL_IMAGES_AMOUNT = 1